todo/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
        url(r'^$',          views.home,     name='home'),
        url(r'^all$',       views.home_all, name='home_all'),
        url(r'^create$',    views.create,   name='create_item'),
        url(r'^delete$',    views.delete,   name='delete_item'),
        url(r'^modify$',    views.modify,   name='modify_item'),
        url(r'^archive$',   views.archive,  name='archive_item'),
    ]

todo_project/urls.py
"""todo_project URL Configuration"""

from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^',           include('todo.urls', namespace="todo") ),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/',     include(admin.site.urls)),
]

todo/models.py
from django.db import models

class todoitem(models.Model):
    todo_line = models.CharField("A To-Do item", max_length=200)
    pub_date = models.DateTimeField('date published',auto_now_add=True)
    todo_done = models.BooleanField(default=False)
    done_date = models.DateTimeField('date the item was marked as done',blank=True,null=True)
    order = models.PositiveIntegerField(editable=False,db_index=True,default=0)

    def __unicode__(self):
        return self.todo_line

todo/views.py
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils import timezone

from .models import todoitem


def home(request):
    todolist = todoitem.objects.filter(todo_done=False).order_by('-pub_date')
    return render(request, 'todo/home.html', {'todolist': todolist})

def home_all(request):
    todolist = todoitem.objects.all().order_by('-pub_date')
    return render(request, 'todo/home.html', {'todolist': todolist})

def create(request):
    if request.method == "POST":
        new_item = todoitem()
        new_item.todo_line = request.POST.get('item_text','')
        new_item.save()
        return redirect('todo:home')
    else:
        return HttpResponse("This is a POST only endpoint.")

@csrf_exempt
def archive(request):
    if request.method == "POST":
        id_of_item_to_archive= request.POST.get('item_to_archive')
        item_to_archive= todoitem.objects.filter(id=id_of_item_to_archive)
        item_to_archive.update(todo_done=True)
        item_to_archive.update(done_date=timezone.now())
        return HttpResponse("OK")
    else:
        return HttpResponse("This is a POST only endpoint.")

def modify(request):
    if request.method == "POST":
        item_to_modify= request.POST.get('item_to_modify')
        item_to_modify_new_line = request.POST.get('item_to_modify_new_line')
        modify_item = todoitem.objects.filter(id=item_to_modify)
        modify_item.update(todo_line=item_to_modify_new_line)
        return redirect('todo:home')
    else:
        return HttpResponse("This is a POST only endpoint.")

@csrf_exempt
def delete(request):
    if request.method == "POST":
        id_of_item_to_delete = request.POST.get('item_to_delete')
        item_to_delete = todoitem.objects.filter(id=id_of_item_to_delete)
        item_to_delete.delete()
        return HttpResponse("OK")
    else:
        return HttpResponse("This is a POST only endpoint.")

todo/templates/todo/base.html
<!DOCTYPE html>{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> 
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
    <title>To-Do App</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/callout.css' %}"/>
<script type="text/javascript" src="{% static 'js/jquery-2.2.4.js' %}"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

    {% block header %}{% endblock header %}
  </head>

  <body>
    <div class="container">
{% block content %} {% endblock content %}
{% block footer %} {% endblock footer %}
    </div> <!-- container-->
  </body>
</html>

todo/templates/todo/home.html
{% extends 'todo/base.html' %}{% load staticfiles %}

{% block content%}

<form action="{% url 'todo:create_item' %}" method="POST" style="margin-top:2em;" >
<div class="input-group">
  <span class="input-group-btn"><button class="btn btn-default btn-lg" style="border-radius:0 !important;" type="button"><span class="glyphicon glyphicon-menu-hamburger"></span></button></span>
  <input style="border-radius:0 !important;" name="item_text" class="form-control input-lg" id="todoitem" aria-describedby="sizing-addon1" placeholder="New item" tabindex="0" autofocus autocomplete="off" />
  {% csrf_token %}
  <span class="input-group-btn"><button class="btn btn-default btn-lg" style="border-radius:0 !important;" type="submit">Add</button></span>
</div><!-- input-group -->
</form>

{% if todolist %}

<div id="todolist">
{% for item in todolist %}
<div class="bs-callout bs-callout-black" id="{{ item.id }}">
  <button type="button" class="close" onclick=" delete_item('{{ item.id }}')" ><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
  <button type="button" class="close" data-toggle="modal" data-target="#editModal" data-newline="{{ item.todo_line }}" data-itemid="{{ item.id }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></button>
  <button type="button" class="close" onclick="archive_item('{{ item.id }}')" ><span class="glyphicon glyphicon-ok"     aria-hidden="true"></span></button>

{% if item.todo_done %}
  <h4 id="callout-content"><del>{{ item.todo_line }}</del></h4>
{% else %}
  <h4 id="callout-content">{{ item.todo_line }}</h4>
{% endif %}

</div> <!-- callout -->
{% endfor %}
</div> <!-- todolist div -->

<!-- hidden modal that displays a form for editing an item -->
<div class="modal bs-example-modal-lg" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit selected item:</h4>
      </div>

      <div class="modal-body" style="padding: 5px;">
        <form action="{% url 'todo:modify_item' %}" method="POST" >
        <div class="input-group">
          <input style="border-radius:0 !important;" name="item_to_modify_new_line" class="form-control input-lg" id="item_to_modify_new_line" aria-describedby="sizing-addon1" placeholder="New item" tabindex="0" autofocus autocomplete="off" /> 
          <input type="hidden" id="item_to_modify" />
          {% csrf_token %}
          <span class="input-group-btn"><button class="btn btn-default btn-lg" style="border-radius:0 !important;" type="submit">apply</button></span>
        </div><!-- input-group -->
        </form>
      </div> <!-- modal-body -->

    </div> <!-- modal-content -->
  </div> <!-- modal-dialog -->
</div> <!-- modal -->

<script type="text/javascript">

$('#editModal').on('show.bs.modal',function (event) {
  var button = $(event.relatedTarget) // button that triggered the modal
  var currentline = button.data('newline') // where to get the initial data from 
  var itemid = button.data('itemid') // where to get the initial data from 
  var modal = $(this)
  modal.find('.modal-body input').val(currentline)
  modal.find('.modal-body #id_of_item_to_modify').val(itemid)
})


function delete_item(item) {
  $.ajax({
    url : "{% url 'todo:delete_item' %}",
    type : "POST",
    data : { item_to_delete : item},
    success: function() {
      $('#'+item).remove();
    },
  });
}

function archive_item(item) {
  $.ajax({
    url : "{% url 'todo:archive_item' %}",
    type : "POST",
    data : { item_to_archive: item},
    success: function() {
      $('#'+item).remove();
    },
  });
}

</script>

{% else %}
<div class="blockquote">Start your todo list now.</div>
{% endif %}

<link rel="stylesheet" href="{% static 'css/dragula.min.css' %}"/>
<script src="{% static 'js/dragula.min.js' %}"></script>
<script type="text/javascript"> dragula([document.querySelector('#todolist')]); </script>
{% endblock content %}